### ISSUE TITLE
Scrolling over Certain Events Causes GDS Crash

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#1686] opened 2022-09-30 01:27 UTC
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

Scrolling over certain Events causes an untraceable Vue.js crash.

**Comment by thomas-bc** [comment] 2024-03-22 00:27
Has not been re-reported since, and not able to reproduce. Closing for now.

**Closed by thomas-bc** 2024-03-22 00:27 UTC
Labels: bug, need-to-reproduce
