### ISSUE TITLE
fprime-util new deployment error

### ISSUE THREAD

**Issue by timcanham** [nasa/fprime#2913] opened 2024-10-02 15:25 UTC
| | |
|:---|:---|
|**_F´ Version_**|[v3.4.3](https://github.com/nasa/fprime/releases/tag/v3.4.3) |
|**_Affected Component_**|  n/a |
---
## Problem Description

When using `fprime-util new deployment`, it compiles with the following error.

```
gmake[3]: *** [GSAT/Top/CMakeFiles/GSAT_Top.dir/build.make:238: GSAT/Top/GSATPacketsAc.cpp] Error 255
gmake[2]: *** [CMakeFiles/Makefile2:6339: GSAT/Top/CMakeFiles/GSAT_Top.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:6264: GSAT/CMakeFiles/GSAT.dir/rule] Error 2
gmake: *** [Makefile:1664: GSAT] Error 2
Packet XML parsing error: Channel systemResources.FRAMEWORK_VERSION does not exist
```

## Context / Environment

Execute `fprime-util version-check` and share the output.

```
Operating System: Linux
CPU Architecture: x86_64
Platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python version: 3.10.12
CMake version: 3.30.2
Pip version: 22.0.2
Pip packages:
    fprime-tools==3.4.5a1
    fprime-gds==3.4.4a3
    fprime-fpp-*==2.2.0a4

```

## How to Reproduce

1. Create a new repo
2. Execute `fprime-util new deployment`
3. Build

## Expected Behavior

Should build without errors.

**Comment by thomas-bc** [comment] 2024-10-02 16:25
This error would appear if you are running with F´ on `devel`. The deployment created by `fprime-util --deployment` should build correctly with the latest release (`v3.4.3`), which also should be the version that's checked out by default by `fprime-bootstrap project`.
Can you confirm this is what you experienced?

In `v3.4.3` systemResources still had a FRAMEWORK_VERSION channel, which is now gone in `devel`.

**Comment by timcanham** [comment] 2024-10-02 16:30
Yes, I was using devel.

**Comment by thomas-bc** [comment] 2024-10-08 20:51
Closing as a duplicate of #2915

**Closed as completed by thomas-bc** 2024-10-08 20:51 UTC
Labels: bug, F´ Tools
