### ISSUE TITLE
generate error: `fpp-depend appears corrupt` on WSL1 with v3.4.0

### ISSUE THREAD

**Issue by ethancheez** [nasa/fprime#2398] opened 2023-11-29 22:48 UTC
| | |
|:---|:---|
|**_F´ Version_**| v3.4.0 |
|**_Affected Component_**|   |
---
## Problem Description

See Error after running `fprime-util generate`:
```
fprime-util generate
[INFO] Generating build directory at: /home/ethan/work/fprime-projects/fprime-community/fprime-tutorial-hello-world/build-fprime-automatic-native
[INFO] Using toolchain file None for platform default
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
/home/ethan/venv/fprime-new/bin/fpp-depend: 1: Syntax error: "(" unexpected
-- [fpp-tools] fpp-depend appears corrupt.
CMake Error at fprime/cmake/required.cmake:26 (message):
-- Configuring incomplete, errors occurred!
   fpp tools not found. Install with:
    'pip install -r "/home/ethan/work/fprime-projects/fprime-community/fprime-tutorial-hello-world/fprime/requirements.txt"'
Call Stack (most recent call first):
  fprime/cmake/FPrime.cmake:13 (include)
  CMakeLists.txt:13 (include)
```

## How to Reproduce

The following commands were executed in order:
```
pip install fprime-tools
pip install -r "fprime/requirements.txt"
fprime-util generate
```

**Comment by thomas-bc** [comment] 2023-11-29 23:02
@ethancheez I haven't been able to reproduce your issue. Do you have more info/context? What about running 
```
pip install -Ur fprime/requirements
```
to make sure packages have been upgraded?

Or maybe try with a fresh virtual environment.

**Comment by ethancheez** [comment] 2023-11-29 23:02
Yes I have made an entirely new virtual environment, and also added the `-Ur` flag. Same error

**Comment by thomas-bc** [comment] 2023-11-29 23:06
And you are using hello-world tutorial v3.4.0 correct?
Can you let me know what host/OS you're using, and version of Python?

Could you also paste the result of `pip freeze | grep fprime`

**Comment by ethancheez** [comment] 2023-11-29 23:13
Yes, latest release of the hello-world-tutorial. v3.4.0. The same error occurs for any other project I have running F' v3.4.0, I used hello-world as an example. And as a side note, I created a fresh project from scratch and ran into the same error running these commands:
```sh
fprime-util new --project
cd NewProject
fprime-util generate
```

Running Windows 11, WSL Ubuntu 22.04.
Python 3.10.12

```
fprime-fpl-convert-xml==1.0.1a4
fprime-fpl-extract-xml==1.0.1a4
fprime-fpl-layout==1.0.1a4
fprime-fpl-write-pic==1.0.1a4
fprime-fpp-check==2.0.1
fprime-fpp-depend==2.0.1
fprime-fpp-filenames==2.0.1
fprime-fpp-format==2.0.1
fprime-fpp-from-xml==2.0.1
fprime-fpp-locate-defs==2.0.1
fprime-fpp-locate-uses==2.0.1
fprime-fpp-syntax==2.0.1
fprime-fpp-to-cpp==2.0.1
fprime-fpp-to-json==2.0.1
fprime-fpp-to-xml==2.0.1
fprime-gds==3.4.0
fprime-tools==3.4.0
fprime-visual==1.0.1
```

**Comment by ethancheez** [comment] 2023-12-01 06:06
WSL 1 seems to be the culprit. WSL 2 works. I was using WSL 1 for the `/dev/tty` ports (for `fprime-gds`) because WSL 2 cannot access the Windows COM ports.

Odd, WSL 1 works fine for the previous fprime/fpp releases.

**Comment by thomas-bc** [comment] 2023-12-01 17:58
Oh interesting... thanks for the info! We'll investigate

**Comment by jsilveira1409** [comment] 2023-12-03 14:07
I'm having the exact same issue on a fresh install of fprime, however, it is on Ubuntu 22 :(

**Comment by thomas-bc** [comment] 2023-12-04 19:38
Dumping some investigation notes in here, unsure whether it is related just yet:

One of the latest successful run building fpp native images https://github.com/fprime-community/fpp/actions/runs/6459740810/job/17540152759 includes this warning. If not related to the current issue, it most certainly is related to the recent fails we've seen in the build
```
        ********************************************************************************
        The arguments ['--plat-name=manylinux_2_28_x86_64'] were given via `--global-option`.
        Please use `--build-option` instead,
        `--global-option` is reserved for flags like `--verbose` or `--quiet`.

        This deprecation is overdue, please update your project and remove deprecated
        calls to avoid build errors in the future.
        ********************************************************************************
```

Ticket on pip : https://github.com/pypa/pip/issues/11859

**Comment by thomas-bc** [comment] 2023-12-04 20:13
@ethancheez @jsilveira1409 would you be able to let me know which version of Python and pip you are running?
```
python --version && pip --version
```


I managed to get a similar issue on WSL2, although it's not exactly the same one so I'm not sure if this will help. Instead of the fpp-depend script being corrupted, it wasn't being installed at all. This was due to me having a too old version of pip on my machine.
Running `pip install --upgrade pip` did the trick, and I'm able to run `fprime-util generate` on WSL2 with F´ v3.4.0.

Can you confirm when the `fprime-fpp-depend` package gets installed, which wheel it's using?
It should read something like
```
fprime_fpp_depend-2.0.1-py3-none-manylinux_2_28_x86_64.whl
```
and **not**
```
fprime_fpp_depend-2.0.1-py3-none-any.whl
```

**Comment by ethancheez** [comment] 2023-12-04 20:18
For WSL2, Ubuntu 22.04

```
Python 3.10.12
pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)
```

```
Collecting fprime-fpp-depend==2.0.1
  Using cached fprime_fpp_depend-2.0.1-py3-none-manylinux_2_28_x86_64.whl (9.2 MB)
```

**Comment by thomas-bc** [comment] 2023-12-04 20:33
What happens if you run `fpp-depend --help` ?

**Comment by ethancheez** [comment] 2023-12-04 20:34
```
fpp-depend v2.0.1
Usage: fpp-depend [options] [file ...]

  -h, --help               print this message and exit
  -a, --auto-test-helpers  enable automatic generation of test helper code
  -d, --direct <file>      write direct dependencies to file
  -f, --framework <file>   write framework dependencies to file
  -g, --generated <file>   write names of generated autocode files to file
  -i, --included <file>    write included dependencies to file
  -m, --missing <file>     write missing dependencies to file
  -u, --unit-test <file>   write names of generated unit test files to file
  file ...                 input files
```

**Comment by thomas-bc** [comment] 2023-12-04 20:40
Ohhh wot

Then maybe all you need is `fprime-util generate -DFPRIME_SKIP_TOOLS_VERSION_CHECK=ON`, this will skip the [tool check](https://github.com/nasa/fprime/blob/0ed8e0b74e2cc99e519576f6cfc250e7d21ca10c/cmake/autocoder/fpp.cmake#L36-L48). I'm not sure why it's tripping...

**Comment by ethancheez** [comment] 2023-12-04 20:45
Trying on my WSL1 Ubuntu 22.04 environment:
```
Python 3.11.0rc1
pip 23.3.1 from /root/venv/fprime/lib/python3.11/site-packages/pip (python 3.11)
```

Results in another error:
```
# fprime-util generate -DFPRIME_SKIP_TOOLS_VERSION_CHECK=ON
[INFO] Generating build directory at: /root/fprime-projects/TestProject/build-fprime-automatic-native
[INFO] Using toolchain file None for platform default
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- [python3] python3 found at: /root/venv/fprime/bin/python3
-- [fpp-tools] fpp-depend found at: /root/venv/fprime/bin/fpp-depend
-- [fpp-tools] fpp-to-xml found at: /root/venv/fprime/bin/fpp-to-xml
-- [fpp-tools] fpp-to-cpp found at: /root/venv/fprime/bin/fpp-to-cpp
-- [fpp-tools] fpp-locate-defs found at: /root/venv/fprime/bin/fpp-locate-defs
-- [FPRIME] Module locations: /root/fprime-projects/TestProject/fprime;/root/fprime-projects/TestProject
-- [FPRIME] Configuration module: /root/fprime-projects/TestProject/fprime/config
-- [FPRIME] Installation directory: /root/fprime-projects/TestProject/build-artifacts
-- Target build toolchain/platform: Linux/Linux
-- Including /root/fprime-projects/TestProject/fprime/cmake/platform/Linux.cmake
-- Requiring thread library
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- [sub-build] Performing sub-build: info-cache
-- [sub-build] Generating: info-cache with target/fpp_locs;target/fpp_depend
-- [sub-build] Executing: info-cache with fpp_locs
CMake Error at fprime/cmake/utilities.cmake:586 (message):
  [sub-build] Failed to execute: info-cache/fpp_locs:

  Traceback (most recent call last):

    File "/root/fprime-projects/TestProject/fprime/cmake/target/tools/redirector.py", line 8, in <module>
      sys.exit(subprocess.run(sys.argv[2:], stdout=file_handle).returncode)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-- Configuring incomplete, errors occurred!
    File "/usr/lib/python3.11/subprocess.py", line 546, in run
      with Popen(*popenargs, **kwargs) as process:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.11/subprocess.py", line 1022, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/usr/lib/python3.11/subprocess.py", line 1899, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)

  OSError: [Errno 8] Exec format error:
  '/root/venv/fprime/bin/fpp-locate-defs'

  gmake[3]: *** [CMakeFiles/fpp_locs.dir/build.make:73: ../locs.fpp] Error 1

  gmake[2]: *** [CMakeFiles/Makefile2:1864: CMakeFiles/fpp_locs.dir/all]
See also "/root/fprime-projects/TestProject/build-fprime-automatic-native/CMakeFiles/CMakeOutput.log".
  Error 2

  gmake[1]: *** [CMakeFiles/Makefile2:1871: CMakeFiles/fpp_locs.dir/rule]
  Error 2

  gmake: *** [Makefile:124: fpp_locs] Error 2
Call Stack (most recent call first):
  fprime/cmake/sub-build/sub-build.cmake:65 (execute_process_or_fail)
  fprime/cmake/FPrime.cmake:149 (run_sub_build)
  fprime/cmake/FPrime.cmake:210 (fprime_initialize_build_system)
  CMakeLists.txt:13 (include)


[ERROR] CMake erred with return code 1. Partial build cache remains. Run purge to clean-up.
```

**Comment by thomas-bc** [comment] 2023-12-04 20:53
Could you try opening `TestProject/fprime/cmake/target/tools/redirector.py` and adding at the very first line:

```
#!/usr/bin/env python3
```

EDIT: nevermind we're actually running the file using `python ...`, not as an executable.
Was reading through [this](https://stackoverflow.com/a/47329417), can you confirm the ouput of 
```
ls -lh <path/to/venv>/bin/fp*
```

**Comment by ethancheez** [comment] 2023-12-04 20:55
> Could you try opening `TestProject/fprime/cmake/target/tools/redirector.py` and adding at the very first line:
> 
> ```
> #!/usr/bin/env python3
> ```

This results in the same error.

**Comment by thomas-bc** [comment] 2023-12-04 20:56
Yeah nevermind we're actually running the file using python ..., not as an executable.

Was reading through [this](https://stackoverflow.com/a/47329417), can you confirm the ouput of

```
ls -lh <path/to/venv>/bin/fp*
```

**Comment by ethancheez** [comment] 2023-12-04 20:57
```
-rwxr-xr-x 1 root root 20M Dec  2 14:14 /root/venv/fprime/bin/fpl-convert-xml
-rwxr-xr-x 1 root root 239 Dec  2 14:14 /root/venv/fprime/bin/fpl-extract-xml
-rwxr-xr-x 1 root root 15M Dec  2 14:14 /root/venv/fprime/bin/fpl-layout
-rwxr-xr-x 1 root root 15M Dec  2 14:14 /root/venv/fprime/bin/fpl-write-pic
-rwxr-xr-x 1 root root 34M Dec  2 14:14 /root/venv/fprime/bin/fpp-check
-rwxr-xr-x 1 root root 33M Dec  2 14:14 /root/venv/fprime/bin/fpp-depend
-rwxr-xr-x 1 root root 33M Dec  2 14:14 /root/venv/fprime/bin/fpp-filenames
-rwxr-xr-x 1 root root 32M Dec  2 14:14 /root/venv/fprime/bin/fpp-format
-rwxr-xr-x 1 root root 37M Dec  2 14:14 /root/venv/fprime/bin/fpp-from-xml
-rwxr-xr-x 1 root root 32M Dec  2 14:14 /root/venv/fprime/bin/fpp-locate-defs
-rwxr-xr-x 1 root root 34M Dec  2 14:14 /root/venv/fprime/bin/fpp-locate-uses
-rwxr-xr-x 1 root root 32M Dec  2 14:14 /root/venv/fprime/bin/fpp-syntax
-rwxr-xr-x 1 root root 38M Dec  2 14:14 /root/venv/fprime/bin/fpp-to-cpp
-rwxr-xr-x 1 root root 34M Dec  2 14:14 /root/venv/fprime/bin/fpp-to-json
-rwxr-xr-x 1 root root 36M Dec  2 14:14 /root/venv/fprime/bin/fpp-to-xml
-rwxr-xr-x 1 root root 248 Dec  2 14:14 /root/venv/fprime/bin/fprime-cli
-rwxr-xr-x 1 root root 252 Dec  2 14:14 /root/venv/fprime/bin/fprime-gds
-rwxr-xr-x 1 root root 245 Dec  2 14:14 /root/venv/fprime/bin/fprime-seqgen
-rwxr-xr-x 1 root root 235 Dec  2 14:08 /root/venv/fprime/bin/fprime-util
-rwxr-xr-x 1 root root 237 Dec  2 14:08 /root/venv/fprime/bin/fprime-version-check
-rwxr-xr-x 1 root root 237 Dec  2 14:14 /root/venv/fprime/bin/fprime-visual
```

**Comment by thomas-bc** [comment] 2023-12-04 21:30
And what about `fpp-locate-defs --help` ?

FWIW, I was able to get that same error message on my Mac by overwriting the script `bin/fpp-locate-defs` with an empty file. 
Have you tried running in a virtual environment outside of root?

**Comment by ethancheez** [comment] 2023-12-04 21:36
## WSL1
Running a new venv outside of root and `fpp-locate-defs --help` results in a formatting error. 
Edit: same error when the venv was inside of `/root/` too
```sh
-bash: /venv/fprime/bin/fpp-locate-defs: cannot execute binary file: Exec format error
```

## WSL2
WSL2 works.
```sh
fpp-locate-defs v2.0.1
Usage: fpp-locate-defs [options] [file ...]

  -d, --directory <dir>  base directory
  -h, --help             print this message and exit
  file ...               files to analyze
```

**Comment by thomas-bc** [comment] 2023-12-04 21:38
Does the entire build process succeed on WSL2?

**Comment by ethancheez** [comment] 2023-12-04 21:39
> Does the entire build process succeed on WSL2?

Yes. I have not run into any issues with v3.4.0 on WSL2

**Comment by thomas-bc** [comment] 2023-12-04 21:42
And this may be a dummy question, but did prior versions of F´ ever work with WSL1?

**Comment by ethancheez** [comment] 2023-12-04 21:44
> And this may be a dummy question, but did prior versions of F´ ever work with WSL1?

Yes I have been using WSL1 (when I started working with you guys in May), and have been using it up until the release of v3.4.0.

I have a few projects that still use older versions of FPrime and FPP, all of which work with WSL1.

**Comment by thomas-bc** [comment] 2023-12-04 21:56
Okok. I'm not familiar with WSL1 but there have been changes in how the `fpp-*` binaries are being built, it could be that this broke on WSL1 with the whole "WSL1 is not actually a Linux VM" thing.

I'll defer to @LeStarch as he's the one who worked on this.

**Comment by ethancheez** [comment] 2023-12-04 22:10
For reference, here are the results of running the same commands on WSL1 using previous versions of fprime and fpp:

```sh
# python --version && pip --version
Python 3.10.12
pip 22.0.2 from /venv/fprime3.3.2/lib/python3.10/site-packages/pip (python 3.10)
```

Using [`fprime@ba8f1c6ac`](https://github.com/nasa/fprime/commit/ba8f1c6ac8ca66e860d1c48b3eccee12ee10d7e0) (release v3.3.2)

```sh
# pip freeze | grep fprime
fprime-fpl-convert-xml==1.0.0
fprime-fpl-extract-xml==1.0.0
fprime-fpl-layout==1.0.0
fprime-fpl-write-pic==1.0.0
fprime-fpp==1.3.0
fprime-gds==3.3.2
fprime-tools==3.3.3
fprime-visual==1.0.0
```

```sh
# fpp-depend --help
fpp-depend v1.3.0
Usage: fpp-depend [options] [file ...]

  -d, --direct <file>     write direct dependencies to file
  -f, --framework <file>  write framework dependencies to file
  -g, --generated <file>  write names of generated autocode files to file
  -i, --included <file>   write included dependencies to file
  -m, --missing <file>    write missing dependencies to file
  -h, --help              print this message and exit
  -t, --template <file>   write names of generated template files to file
  file ...                input files
```

```sh
# fpp-locate-defs --help
fpp-locate-defs v1.3.0
Usage: fpp-locate-defs [options] [file ...]

  -d, --directory <dir>  base directory
  -h, --help             print this message and exit
  file ...               files to analyze
```

```sh
# ls -lh /venv/fprime3.3.2/bin/fp*
-rwxr-xr-x 1 root root 20M Dec  4 12:01 /venv/fprime3.3.2/bin/fpl-convert-xml
-rwxr-xr-x 1 root root 235 Dec  4 12:01 /venv/fprime3.3.2/bin/fpl-extract-xml
-rwxr-xr-x 1 root root 15M Dec  4 12:01 /venv/fprime3.3.2/bin/fpl-layout
-rwxr-xr-x 1 root root 15M Dec  4 12:01 /venv/fprime3.3.2/bin/fpl-write-pic
-rwxr-xr-x 1 root root 21M Dec  4 12:01 /venv/fprime3.3.2/bin/fpp-check
-rwxr-xr-x 1 root root 18M Dec  4 12:01 /venv/fprime3.3.2/bin/fpp-depend
-rwxr-xr-x 1 root root 18M Dec  4 12:01 /venv/fprime3.3.2/bin/fpp-filenames
-rwxr-xr-x 1 root root 18M Dec  4 12:01 /venv/fprime3.3.2/bin/fpp-format
-rwxr-xr-x 1 root root 23M Dec  4 12:01 /venv/fprime3.3.2/bin/fpp-from-xml
-rwxr-xr-x 1 root root 18M Dec  4 12:01 /venv/fprime3.3.2/bin/fpp-locate-defs
-rwxr-xr-x 1 root root 21M Dec  4 12:01 /venv/fprime3.3.2/bin/fpp-locate-uses
-rwxr-xr-x 1 root root 18M Dec  4 12:01 /venv/fprime3.3.2/bin/fpp-syntax
-rwxr-xr-x 1 root root 22M Dec  4 12:01 /venv/fprime3.3.2/bin/fpp-to-cpp
-rwxr-xr-x 1 root root 21M Dec  4 12:01 /venv/fprime3.3.2/bin/fpp-to-xml
-rwxr-xr-x 1 root root 244 Dec  4 12:01 /venv/fprime3.3.2/bin/fprime-cli
-rwxr-xr-x 1 root root 248 Dec  4 12:01 /venv/fprime3.3.2/bin/fprime-gds
-rwxr-xr-x 1 root root 241 Dec  4 12:01 /venv/fprime3.3.2/bin/fprime-seqgen
-rwxr-xr-x 1 root root 231 Dec  4 12:01 /venv/fprime3.3.2/bin/fprime-util
-rwxr-xr-x 1 root root 233 Dec  4 12:01 /venv/fprime3.3.2/bin/fprime-version-check
-rwxr-xr-x 1 root root 233 Dec  4 12:01 /venv/fprime3.3.2/bin/fprime-visual
```

`fprime-util generate` and `fprime-util build` completes with no error.

**Comment by jsilveira1409** [comment] 2023-12-09 10:32
Got caught up on some work. On Ubuntu 20.04 i'm getting:

```[INFO] Generating build directory at: /home/dphi/Desktop/FS/ClusterGateV2/build-fprime-automatic-aarch64-linux
[INFO] Using toolchain file /home/dphi/Desktop/FS/ClusterGateV2/fprime/cmake/toolchain/aarch64-linux.cmake for platform aarch64-linux
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Check for working C compiler: /opt/toolchains/bin/aarch64-none-linux-gnu-gcc
-- Check for working C compiler: /opt/toolchains/bin/aarch64-none-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/toolchains/bin/aarch64-none-linux-gnu-g++
-- Check for working CXX compiler: /opt/toolchains/bin/aarch64-none-linux-gnu-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- [fpp-tools] Could not find fpp-depend
CMake Error at fprime/cmake/required.cmake:26 (message):
-- Configuring incomplete, errors occurred!
   fpp tools not found. Install with:
See also "/home/dphi/Desktop/FS/ClusterGateV2/build-fprime-automatic-aarch64-linux/CMakeFiles/CMakeOutput.log".
    'pip install -r "/home/dphi/Desktop/FS/ClusterGateV2/fprime/requirements.txt"'
Call Stack (most recent call first):
  fprime/cmake/FPrime.cmake:13 (include)
  CMakeLists.txt:13 (include)
```
  
  running on a venv with the tools already installed. `fpp-depend` does not seem to be found when running `fpp-depend --help`  even after running `pip install -r requirements.txt` and successfully installing it.
  
  currently running: 
  
```  
Python 3.8.10
pip 23.3.1 from prime-venv/lib/python3.8/site-packages/pip (python 3.8)
```
  
`pip freeze | grep fprime` outputs:

```
fprime-fpl-convert-xml==1.0.1a4
fprime-fpl-extract-xml==1.0.1a4
fprime-fpl-layout==1.0.1a4
fprime-fpl-write-pic==1.0.1a4
fprime-fpp-check==2.0.1
fprime-fpp-depend==2.0.1
fprime-fpp-filenames==2.0.1
fprime-fpp-format==2.0.1
fprime-fpp-from-xml==2.0.1
fprime-fpp-locate-defs==2.0.1
fprime-fpp-locate-uses==2.0.1
fprime-fpp-syntax==2.0.1
fprime-fpp-to-cpp==2.0.1
fprime-fpp-to-json==2.0.1
fprime-fpp-to-xml==2.0.1
fprime-gds==3.4.0
fprime-tools==3.4.0
fprime-visual==1.0.1
``` 
  
  
  and yes fpp-depend is installed from the wheel you mentionned @thomas-bc (`fprime_fpp_depend-2.0.1-py3-none-manylinux_2_28_x86_64.whl`)

**Comment by LeStarch** [comment] 2023-12-12 00:48
This looks like v3.4.0 has some bad packages.  The new packages I made today for (prep for v2.0.2 fpp) work just fine.

**Comment by LeStarch** [comment] 2023-12-12 00:58
The only substantial difference I can see is that the new packages are compatible with an older kernel (2.6.32 not 3.2.0).  They also have subtly different sizes....but not of this would cause issue in my estimation.

**Comment by ethancheez** [comment] 2023-12-12 01:03
> This looks like v3.4.0 has some bad packages. The new packages I made today for (prep for v2.0.2 fpp) work just fine.

Any way for me to test this on my WSL1 instance to see if it works? Can I clone [`fprime-tools`](https://github.com/fprime-community/fprime-tools) and just run `pip install -U .` ?

**Comment by LeStarch** [comment] 2023-12-12 01:06
At this point, I will recommend we release the hot fix, v2.0.2 FPP, and test those packages on WSL 1.  If it works, then I'd argue this is a fluke unless we find more corrupt packages.

Unless someone knows how to pin-point what the format error actually is.  The `file` output on the working and not working builds indicate that the file type should be compatible...so it is corruption somewhere in the file, or specific incompatibilities with some platforms.  Both are notoriously hard to reproduce.

**Comment by LeStarch** [comment] 2023-12-12 01:09
This error also implies we should track a checksum of each binary from the time of creation.  Just so we can check to see if something changed during packaging.

**Comment by LeStarch** [comment] 2023-12-12 01:42
> > This looks like v3.4.0 has some bad packages. The new packages I made today for (prep for v2.0.2 fpp) work just fine.
> 
> Any way for me to test this on my WSL1 instance to see if it works? Can I clone [`fprime-tools`](https://github.com/fprime-community/fprime-tools) and just run `pip install -U .` ?

Not easily.  These are interim packages that are built as part of the normal build...but only maintainers have access to the artifacts. However, we are about to do the point release and you could test that!

**Comment by LeStarch** [comment] 2023-12-13 23:12
@ethancheez you should now be able to install via `pip install fprime-fpp==v2.0.2a1` and test the new corrected packages.  Note: this uses our new meta-package for ease of installation of the whole suite.  Make sure all the individual tool packages update.

Also, you'll need to bump fpp versions in requirements.txt or run with -DFPRIM_SKIP_TOOLS_VERSION_CHECK=ON

**Comment by ethancheez** [comment] 2023-12-13 23:31
> @ethancheez you should now be able to install via `pip install fprime-fpp==v2.0.2a1` and test the new corrected packages. Note: this uses our new meta-package for ease of installation of the whole suite. Make sure all the individual tool packages update.
> 
> Also, you'll need to bump fpp versions in requirements.txt or run with -DFPRIM_SKIP_TOOLS_VERSION_CHECK=ON

Successfully generates and builds for native Linux on WSL1!

**Comment by LeStarch** [comment] 2023-12-14 16:48
Wooo!  I am going to close this issue as it seems we fixed this.

**Closed as completed by LeStarch** 2023-12-14 16:48 UTC
Labels: bug
