### ISSUE TITLE
Write loaders for new dictionary

### ISSUE THREAD

**Issue by jwest115** [nasa/fprime#2399] opened 2023-11-29 22:53 UTC
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

A description of the problem with sufficient detail to understand the issue.

## How to Reproduce

1. 
2.
3.

## Expected Behavior

A description of the expected behavior.

**Comment by thomas-bc** [comment] 2024-03-22 00:02
Duplicate of https://github.com/nasa/fprime/issues/2592

**Closed as not planned by thomas-bc** 2024-03-22 00:02 UTC
