### ISSUE TITLE
fprime-util install not recognised

### ISSUE THREAD

**Issue by dagamargit** [nasa/fprime#428] opened 2021-03-02 16:45 UTC
| | |
|:---|:---|
|**F´ Release 1.5.3**| |
|**_Installation **|   |
---
## Problem Description

First f-prime installation on WSL2 Debian. Following instructions included at:
https://nasa.github.io/fprime/INSTALL.html

fprime-util install --jobs 32 is not recognised:

usage: fprime-util [-h]
                   {generate,purge,hash-to-file,info,build,impl,check} ...
fprime-util: error: argument command: invalid choice: 'install' (choose from 'generate', 'purge', 'hash-to-file', 'info', 'build', 'impl', 'check')

## How to Reproduce

Just follow instructions at https://nasa.github.io/fprime/INSTALL.html until "Checking Your F´ Installation"

The order "fprime-util install --jobs 32" doesn't work

## Expected Behavior
Binary to execute Ref application

**Comment by Joshua-Anderson** [comment] 2021-03-02 17:38
The documentation on the website is for the last release of fprime, 1.5. In the development version of fprime we refactored fprime-util to remove the install command. Instead of needing to build and install, you just need to build with `fprime-util build`.

If you look at our documentation in the devel branch, you'll see the updated install guide - https://github.com/nasa/fprime/blob/devel/docs/INSTALL.md

When we do the next fprime release this version of the documentation will automatically go live on the website.
I'd either switch to the last fprime release or look at the documentation for the development version.

I'm closing this because it's not a bug, but feel free to follow up with any questions you have!

**Closed by Joshua-Anderson** 2021-03-02 17:38 UTC
Labels: bug
